---
- name: install python and docker essentials
  become: true
  package:
      name: "python3-pip"
      update_cache: yes

- name: Add user to docker group
  become: true
  user:
      name: ubuntu
      groups: docker
      append: yes

- name: Add user to docker group
  become: true
  user:
      name: vagrant
      groups: docker
      append: yes

- name: Make sure vital python packages are installed system-wide 
  become: true
  pip:
    name: docker-py
    state: latest

- name: Pull NGB docker container
  become: true
  docker_image:
    name: umccr/ngb
    tag: latest
    state: present

# XXX: pull in reference genomes (hg38 and GRC37h) and add input dataset(s)
# ngb reg_ref /ngs/hg38_new/hg38_elongated_telomeres.fa -n 10x_telomeres_ref_elongated -t
# ngb reg_file 10x_telomeres_ref_elongated /ngs/COLO829BL_bwa_truseq_hg38.bam -t
# ngb reg_dataset 10x_telomeres_ref_elongated COLO829BL_bwa_truseq_hg38.bam COLO829BL_bwa_truseq_hg38.bam

- name: Run NGB
  become: true
  docker_container:
    name: ngbcore
    image: lifescience/ngb
    state: started
    ports:
        - "8080:8080"
    volumes:
        - "/mnt:/ngs"